version: '2' #docker-compose version

#Define the services and containers
services:
  database: #Service name
    image: mongo #Image to build container from
    ports:
      - "27017:27017"

  express: #Service name
    build: express #Directory of the Dockerfile
    ports:
      - "3000:3000"
    links:
      - database

  angular: #Service name
    build: angular #Directory of the Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./angular:/app #Trigger recompilation in container
